[theme]
# Primary accent color for interactive elements.
primaryColor = "#50394c"

# Background color for the main content area.
backgroundColor = "#f0f0f0"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#b0aac0"

# Color used for almost all text.
textColor = "#50394c"